# Accessing Specific Column

Series: 
When we select a single column, we’re actually getting a Pandas Series (not a full DataFrame).
If a DataFrame is like a table, a Series is like a single column of that table. It’s still powerful, just narrower.

In [15]:
import pandas as pd
characters_data = {
  'name': ['Thorne', 'Elira', 'Glim', 'Brug', 'Nyx', 'Kael', 'Mira', 'Drogan', 'Zara', 'Fenwick'],
  'race': ['Elf', 'Human', 'Gnome', 'Half-Orc', 'Tiefling', 'Dragonborn', 'Halfling', 'Dwarf', 'Aasimar', 'Goblin'],
  'class': ['Ranger', 'Cleric', 'Wizard', 'Barbarian', 'Rogue', 'Paladin', 'Bard', 'Fighter', 'Sorcerer', 'Warlock'],
  'level': [5, 3, 4, 2, 6, 7, 3, 5, 4, 2],
  'hp': [42, 28, 33, 25, 48, 56, 30, 44, 36, 24],
  'alignment': [
    'Chaotic Good', 'Lawful Good', 'Neutral', 'Chaotic Neutral', 'Chaotic Evil',
    'Lawful Neutral', 'Neutral Good', 'Neutral', 'Chaotic Good', 'Lawful Evil'
  ]
}
characters=pd.DataFrame(characters_data)

In [16]:
characters

      name        race      class  level  hp        alignment
0   Thorne         Elf     Ranger      5  42     Chaotic Good
1    Elira       Human     Cleric      3  28      Lawful Good
2     Glim       Gnome     Wizard      4  33          Neutral
3     Brug    Half-Orc  Barbarian      2  25  Chaotic Neutral
4      Nyx    Tiefling      Rogue      6  48     Chaotic Evil
5     Kael  Dragonborn    Paladin      7  56   Lawful Neutral
6     Mira    Halfling       Bard      3  30     Neutral Good
7   Drogan       Dwarf    Fighter      5  44          Neutral
8     Zara     Aasimar   Sorcerer      4  36     Chaotic Good
9  Fenwick      Goblin    Warlock      2  24      Lawful Evil

In [17]:
#Accessing Single column
characters_name=characters['name']
characters_name

0     Thorne
1      Elira
2       Glim
3       Brug
4        Nyx
5       Kael
6       Mira
7     Drogan
8       Zara
9    Fenwick
Name: name, dtype: object

In [21]:
type(characters_name)

pandas.core.series.Series

In [22]:
type(characters)

pandas.core.frame.DataFrame

In [23]:
#Accessing Multiple Columns
df=characters[['race','level']]
df

         race  level
0         Elf      5
1       Human      3
2       Gnome      4
3    Half-Orc      2
4    Tiefling      6
5  Dragonborn      7
6    Halfling      3
7       Dwarf      5
8     Aasimar      4
9      Goblin      2

In [7]:
type(df)  #It gives dataframe because it is selecting more than one column and not a single column

pandas.core.frame.DataFrame

In [24]:
#Accessing all but one column with .drop()
remove_alignment_df=characters.drop("alignment",axis=1)
remove_alignment_df

      name        race      class  level  hp
0   Thorne         Elf     Ranger      5  42
1    Elira       Human     Cleric      3  28
2     Glim       Gnome     Wizard      4  33
3     Brug    Half-Orc  Barbarian      2  25
4      Nyx    Tiefling      Rogue      6  48
5     Kael  Dragonborn    Paladin      7  56
6     Mira    Halfling       Bard      3  30
7   Drogan       Dwarf    Fighter      5  44
8     Zara     Aasimar   Sorcerer      4  36
9  Fenwick      Goblin    Warlock      2  24

# Accessing a row

In [25]:
df.loc[[0,1]]

    race  level
0    Elf      5
1  Human      3

In [28]:
df.loc[[4,5]][level,hp]

NameError: name 'level' is not defined

# Find Missing values

In [2]:
import numpy as np
import pandas as pd

In [3]:
data={
    'A':[1,2,np.nan,4,5],
    'B':[np.nan,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)

In [4]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [5]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [6]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [7]:
# It will see whether is there any column in a table which have nan value
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool