In [2]:
#Four pandas methods that can help with some basic data exploration:
#1 .head() & .tail()
#2 .info()
#3 .describe()

In [22]:
import pandas as pd
data={ 'city':['Brooklyn','Seoul','Barcelona','Mexico City','Bhopal','Tokyo','Sanghai','Brussels','Colombia','Phatak'],
     'country':['US','South Korea','Spain','Mexico','India','Japan','China','Belgium','Sri Lanka','Thailand'],
     'population':[2646000, 9411000, 1636000, 9209944,74648338,8483939,None,738393,None,748473839]}

In [25]:
df=pd.DataFrame(data)
df

          city      country   population
0     Brooklyn           US    2646000.0
1        Seoul  South Korea    9411000.0
2    Barcelona        Spain    1636000.0
3  Mexico City       Mexico    9209944.0
4       Bhopal        India   74648338.0
5        Tokyo        Japan    8483939.0
6      Sanghai        China          NaN
7     Brussels      Belgium     738393.0
8     Colombia    Sri Lanka          NaN
9       Phatak     Thailand  748473839.0

In [24]:
#.head()
df.head()

          city      country  population
0     Brooklyn           US   2646000.0
1        Seoul  South Korea   9411000.0
2    Barcelona        Spain   1636000.0
3  Mexico City       Mexico   9209944.0
4       Bhopal        India  74648338.0

In [7]:
#.tail()
df.tail()

       city    country  population
5     Tokyo      Japan     8483939
6   Sanghai      China           0
7  Brussels    Belgium      738393
8  Colombia  Sri Lanka           0
9    Phatak   Thailand   748473839

In [9]:
#to fetch number of columns
df.head(7)

          city      country  population
0     Brooklyn           US     2646000
1        Seoul  South Korea     9411000
2    Barcelona        Spain     1636000
3  Mexico City       Mexico     9209944
4       Bhopal        India    74648338
5        Tokyo        Japan     8483939
6      Sanghai        China           0

In [10]:
#.info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   city        10 non-null     object
 1   country     10 non-null     object
 2   population  10 non-null     int64
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

In [16]:
#describe()  --> this only describes for the numeric column
df.describe()

         population
count  1.000000e+01
mean   8.552475e+07
std    2.340219e+08
min    0.000000e+00
25%    9.627948e+05
50%    5.564970e+06
75%    9.360736e+06
max    7.484738e+08

In [18]:
#to know about all the columns
df.describe(include='all')

            city country    population
count         10      10  1.000000e+01
unique        10      10           NaN
top     Brooklyn      US           NaN
freq           1       1           NaN
mean         NaN     NaN  8.552475e+07
std          NaN     NaN  2.340219e+08
min          NaN     NaN  0.000000e+00
25%          NaN     NaN  9.627948e+05
50%          NaN     NaN  5.564970e+06
75%          NaN     NaN  9.360736e+06
max          NaN     NaN  7.484738e+08