# DATAFRAME

In [1]:
import pandas as pd

In [3]:
#Creating a dataframe 
#1. Creating it from dictionary

data={ 'city':['Brooklyn','Seoul','Barcelona','Mexico City'],
     'country':['US','South Korea','Spain','Mexico'],
     'population':[2646000, 9411000, 1636000, 9209944]}
df=pd.DataFrame(data)

In [4]:
df

          city      country  population
0     Brooklyn           US     2646000
1        Seoul  South Korea     9411000
2    Barcelona        Spain     1636000
3  Mexico City       Mexico     9209944

In [7]:
#2. Creating from a list of Lists
data=[['Brooklyn','US',2646000],
['Seoul', 'South Korea', 9411000],
  ['Barcelona', 'Spain', 1636000],
  ['Mexico City', 'Mexico', 9209944]]
df=pd.DataFrame(data,columns=['city','country', 'population'])

In [8]:
df

          city      country  population
0     Brooklyn           US     2646000
1        Seoul  South Korea     9411000
2    Barcelona        Spain     1636000
3  Mexico City       Mexico     9209944

In [10]:
#3. Import from a CSV file
#df=pd.read_csv('my_filename.csv)