# Filter rows

In [1]:
import pandas as pd
characters_data = {
  'name': ['Thorne', 'Elira', 'Glim', 'Brug', 'Nyx', 'Kael', 'Mira', 'Drogan', 'Zara', 'Fenwick'],
  'race': ['Elf', 'Human', 'Gnome', 'Half-Orc', 'Tiefling', 'Dragonborn', 'Halfling', 'Dwarf', 'Aasimar', 'Goblin'],
  'class': ['Ranger', 'Cleric', 'Wizard', 'Barbarian', 'Rogue', 'Paladin', 'Bard', 'Fighter', 'Sorcerer', 'Warlock'],
  'level': [5, 3, 4, 2, 6, 7, 3, 5, 4, 2],
  'hp': [42, 28, 33, 25, 48, 56, 30, 44, 36, 24],
  'alignment': [
    'Chaotic Good', 'Lawful Good', 'Neutral', 'Chaotic Neutral', 'Chaotic Evil',
    'Lawful Neutral', 'Neutral Good', 'Neutral', 'Chaotic Good', 'Lawful Evil'
  ]
}
characters=pd.DataFrame(characters_data)

In [2]:
characters

      name        race      class  level  hp        alignment
0   Thorne         Elf     Ranger      5  42     Chaotic Good
1    Elira       Human     Cleric      3  28      Lawful Good
2     Glim       Gnome     Wizard      4  33          Neutral
3     Brug    Half-Orc  Barbarian      2  25  Chaotic Neutral
4      Nyx    Tiefling      Rogue      6  48     Chaotic Evil
5     Kael  Dragonborn    Paladin      7  56   Lawful Neutral
6     Mira    Halfling       Bard      3  30     Neutral Good
7   Drogan       Dwarf    Fighter      5  44          Neutral
8     Zara     Aasimar   Sorcerer      4  36     Chaotic Good
9  Fenwick      Goblin    Warlock      2  24      Lawful Evil

In [4]:
#To filter hp colmns more than 30 entry
hp_filtered=characters[characters["hp"]>30]
hp_filtered

     name        race     class  level  hp       alignment
0  Thorne         Elf    Ranger      5  42    Chaotic Good
2    Glim       Gnome    Wizard      4  33         Neutral
4     Nyx    Tiefling     Rogue      6  48    Chaotic Evil
5    Kael  Dragonborn   Paladin      7  56  Lawful Neutral
7  Drogan       Dwarf   Fighter      5  44         Neutral
8    Zara     Aasimar  Sorcerer      4  36    Chaotic Good

characters["hp"]>30] creates a Series of True and False values, one for each row

In [6]:
#we can do the above code like the other one
boolean_series = characters['hp'] > 30
long_hp = characters[boolean_series]
long_hp

     name        race     class  level  hp       alignment
0  Thorne         Elf    Ranger      5  42    Chaotic Good
2    Glim       Gnome    Wizard      4  33         Neutral
4     Nyx    Tiefling     Rogue      6  48    Chaotic Evil
5    Kael  Dragonborn   Paladin      7  56  Lawful Neutral
7  Drogan       Dwarf   Fighter      5  44         Neutral
8    Zara     Aasimar  Sorcerer      4  36    Chaotic Good

# AND  and OR

We can filter based on multiple conditions by using AND (&) and OR (|)

In [7]:
#Using AND (&)

In [8]:
#halfling_bards that contains all characters whose race is 'Halfling' AND whose class is 'Bard'.
halfing_bards=characters[(characters["race"]=="Halfling") & (characters["class"]=="Bard")]
halfing_bards

   name      race class  level  hp     alignment
6  Mira  Halfling  Bard      3  30  Neutral Good

In [9]:
#Using OR(|)

In [10]:
#magic_users that contains all characters whose class is Wizard OR Sorcerer OR Warlock.
magic_users = characters[
    (characters['class'] == 'Wizard') |
    (characters['class'] == 'Sorcerer') |
    (characters['class'] == 'Warlock')
]
magic_users

      name     race     class  level  hp     alignment
2     Glim    Gnome    Wizard      4  33       Neutral
8     Zara  Aasimar  Sorcerer      4  36  Chaotic Good
9  Fenwick   Goblin   Warlock      2  24   Lawful Evil