# Sorting, Renaming, and Adding Columns

In [1]:
import pandas as pd
app_data = {
  'app_name': [
    'YouTube', 'TikTok', 'Instagram', 'Spotify', 'Duolingo', 
    'Twitter', 'Headspace', 'Discord', 'Depop'
  ],
  'category': [
    'Video', 'Social Media', 'Social Media', 'Music', 'Education',
    'Social Media', 'Health', 'Communication', 'Shopping'
  ],
  'rating': [
    4.7, 4.6, 4.5, 4.6, 4.7,
    4.3, None, 4.7, 4.4
  ],
  'downloads_millions': [
    5000, 3000, 3500, 2000, None,
    1500, 500, 600, 200
  ]
}
apps=pd.DataFrame(app_data)

In [2]:
apps

    app_name       category  rating  downloads_millions
0    YouTube          Video     4.7              5000.0
1     TikTok   Social Media     4.6              3000.0
2  Instagram   Social Media     4.5              3500.0
3    Spotify          Music     4.6              2000.0
4   Duolingo      Education     4.7                 NaN
5    Twitter   Social Media     4.3              1500.0
6  Headspace         Health     NaN               500.0
7    Discord  Communication     4.7               600.0
8      Depop       Shopping     4.4               200.0

# SORTING

Sorting By columns with .sort_values()
--> Here we sort the particular column by using .sort_values()
If we wanted to sort from high to low, just use ascending=True.

In [5]:
#Sort the apps by rating so the highest rated apps are at the top of the DataFrame
sorted=apps.sort_values(by="rating",ascending=False)
sorted

    app_name       category  rating  downloads_millions
0    YouTube          Video     4.7              5000.0
4   Duolingo      Education     4.7                 NaN
7    Discord  Communication     4.7               600.0
1     TikTok   Social Media     4.6              3000.0
3    Spotify          Music     4.6              2000.0
2  Instagram   Social Media     4.5              3500.0
8      Depop       Shopping     4.4               200.0
5    Twitter   Social Media     4.3              1500.0
6  Headspace         Health     NaN               500.0

# RENAMING

Rename Columns with .rename()
To rename the specific column name. we can do that by using .rename()

In [6]:
#Change the name of the column app_name to name
new_name=apps.rename(columns={"app_name":"name"})
new_name

        name       category  rating  downloads_millions
0    YouTube          Video     4.7              5000.0
1     TikTok   Social Media     4.6              3000.0
2  Instagram   Social Media     4.5              3500.0
3    Spotify          Music     4.6              2000.0
4   Duolingo      Education     4.7                 NaN
5    Twitter   Social Media     4.3              1500.0
6  Headspace         Health     NaN               500.0
7    Discord  Communication     4.7               600.0
8      Depop       Shopping     4.4               200.0

# ADDING

Adding columns
we can add columns by assigning a list or a calculation to column name

In [9]:
# Begin by adding a column named downloaded that contains True or False depending on whether you have the app downloaded on your phone.
apps['downloaded']=['True','False','True','False','True','False','True','False','True']

In [10]:
apps

    app_name       category  rating  downloads_millions download
0    YouTube          Video     4.7              5000.0     True
1     TikTok   Social Media     4.6              3000.0    False
2  Instagram   Social Media     4.5              3500.0     True
3    Spotify          Music     4.6              2000.0    False
4   Duolingo      Education     4.7                 NaN     True
5    Twitter   Social Media     4.3              1500.0    False
6  Headspace         Health     NaN               500.0     True
7    Discord  Communication     4.7               600.0    False
8      Depop       Shopping     4.4               200.0     True