# DUPLICATE OF DATA

In [1]:
import pandas as pd
data = {
  'ticket_id': [
    'TKT-88421', 'TKT-88421', 'TKT-99213',
    'TKT-55310', 'TKT-55310', 'TKT-66772',
    'TKT-11890', 'TKT-11890', 'TKT-77445', 
    'TKT-33109', 'TKT-18479', 'TKT-90002'
  ],
  'passenger_name': [
    'Don Draper', 'Don Draper', 'Emily Davis',
    'Roger Sterling', 'Roger Sterling', 'Harper Stern',
    'Pete Campbell', 'Pete Campbell', 'Robert Spearing', 
    'Olivia Martinez', 'Andrew Largeman', 'Kendall Roy'
  ],
  'flight': [
    'PA102', 'PA102', 'DL404',
    'UA220', 'UA220', 'UA178',
    'AA778', 'AA778', 'BA305', 
    'DL909', 'UA347', 'PRV-JET'
  ],
  'route': [
    'LGW → LAX', 'LGA → LAX', 'ATL → SEA',
    'JFK → CDG', 'JFK → CDG', 'JFK → LHR',
    'MCI → LGA', 'MCI → LGA', 'LHR → SFO', 
    'DEN → PHX', 'LAX → EWR', 'NYC → Oslo'
  ]
}
df=pd.DataFrame(data)
df

    ticket_id   passenger_name   flight       route
0   TKT-88421       Don Draper    PA102   LGW → LAX
1   TKT-88421       Don Draper    PA102   LGA → LAX
2   TKT-99213      Emily Davis    DL404   ATL → SEA
3   TKT-55310   Roger Sterling    UA220   JFK → CDG
4   TKT-55310   Roger Sterling    UA220   JFK → CDG
5   TKT-66772     Harper Stern    UA178   JFK → LHR
6   TKT-11890    Pete Campbell    AA778   MCI → LGA
7   TKT-11890    Pete Campbell    AA778   MCI → LGA
8   TKT-77445  Robert Spearing    BA305   LHR → SFO
9   TKT-33109  Olivia Martinez    DL909   DEN → PHX
10  TKT-18479  Andrew Largeman    UA347   LAX → EWR
11  TKT-90002      Kendall Roy  PRV-JET  NYC → Oslo

# Find Duplicate Data with .duplicated()

We can use the .duplicated() method to find rows that are duplicates of each other.
Syntax:  df.duplicated() ---> It returns a Series of True and False values. True means that row is a duplicate

If we wanted to see the actual rows that are duplicates, we could then use this Series as a filter to our DataFrame
Syntax:  df[df.duplicated()] ---> This will return only the rows from the Series that were marked as True.

In [2]:
# Find the duplicate from the given data
duplicate=df.duplicated()
duplicate

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7      True
8     False
9     False
10    False
11    False
dtype: bool

In [3]:
# To see the actual rows that are duplicates
actual_duplicate=df[df.duplicated()]
actual_duplicate

   ticket_id  passenger_name flight      route
4  TKT-55310  Roger Sterling  UA220  JFK → CDG
7  TKT-11890   Pete Campbell  AA778  MCI → LGA

# Remove Duplicates with .drop_duplicates()

Once we know if we have duplicates, we can decide how to remove them. The simplest way is to use .drop_duplicates(). This will remove all rows that are exactly identical to another row in the DataFrame.

Syntax:   no_dupes = df.drop_duplicates()

However, sometimes rows aren’t exact duplicates, but you still want to remove certain repeated values.
For example, in a library catalog, the same book might be entered twice with slightly different author names. The Lord of the Rings might have "JRR Tolkien" as the author while another row might use "J.R.R. Tolkien".
These rows aren’t exact duplicates, so .drop_duplicates() on the whole row won’t work.
Luckily, most datasets have a column that uniquely identifies each row. For a library, this would be the book’s ISBN.

We can tell Pandas to remove duplicates based only on that column using subset:

#Removes rows that have a duplicate ISBN with another row

unique_books = catalog.drop_duplicates(subset = ['ISBN'])   --->Pandas will keep the first row for each unique ISBN and will remove all other rows with duplicated ISBNs.

In [4]:
# create a DataFrame with one row for each unique ticket booking
no_duplicate=df.drop_duplicates()
no_duplicate

    ticket_id   passenger_name   flight       route
0   TKT-88421       Don Draper    PA102   LGW → LAX
1   TKT-88421       Don Draper    PA102   LGA → LAX
2   TKT-99213      Emily Davis    DL404   ATL → SEA
3   TKT-55310   Roger Sterling    UA220   JFK → CDG
5   TKT-66772     Harper Stern    UA178   JFK → LHR
6   TKT-11890    Pete Campbell    AA778   MCI → LGA
8   TKT-77445  Robert Spearing    BA305   LHR → SFO
9   TKT-33109  Olivia Martinez    DL909   DEN → PHX
10  TKT-18479  Andrew Largeman    UA347   LAX → EWR
11  TKT-90002      Kendall Roy  PRV-JET  NYC → Oslo

 Question: We notice that some duplicate bookings still remain. Why? Add a comment explaining what’s happening.
--> drop_duplicates() only removes rows that are exactly identical across the selected columns.
Some duplicate bookings may still remain because there are small differences between the rows, such as in row number 0 and in row number 1 we see it looks mostly same
but there is a slight difference of route due to which it did not get deleted using .drop_duplicates()

to delete those also we use the concept of subset . we will select the column which will uniquely identified the row and give it to a subset

In [6]:
unique_ticket=df.drop_duplicates(subset=['ticket_id'])
unique_ticket

    ticket_id   passenger_name   flight       route
0   TKT-88421       Don Draper    PA102   LGW → LAX
2   TKT-99213      Emily Davis    DL404   ATL → SEA
3   TKT-55310   Roger Sterling    UA220   JFK → CDG
5   TKT-66772     Harper Stern    UA178   JFK → LHR
6   TKT-11890    Pete Campbell    AA778   MCI → LGA
8   TKT-77445  Robert Spearing    BA305   LHR → SFO
9   TKT-33109  Olivia Martinez    DL909   DEN → PHX
10  TKT-18479  Andrew Largeman    UA347   LAX → EWR
11  TKT-90002      Kendall Roy  PRV-JET  NYC → Oslo

#now we see on using the subset ticket_id which help us to uniquely identify each and every row. This result on a dataset with no duplicates present in it
as we know that the ticket id is always unique, no two person can have the same ticket id.