# Missing Mail

In [1]:
import pandas as pd
data = {
  'street': [
    '5230 Newell Road',
    '1381 9th Avenue',
    '1709 Broderick St',
    '2640 Steiner St',
    '2601 Lyon St',
    '1600 Amphitheatre Parkway',
    '7500 N Glenoaks Boulevard',
    '4501 Glencoe Avenue',
    '232 Santa Margarita Ave',
    '471 Emerson Street'
  ],
  'city': [
    'Palo Alto',
    'San Francisco',
    'San Francisco',
    'San Francisco',
    'San Francisco',
    'Mountain View',
    'Burbank',
    'Marina del Rey',
    'Menlo Park',
    None
  ],
  'state': [
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    None,
    None
  ],
  'zip_code': [
    94303,
    94122,
    94115,
    94123,
    94123,
    94043,
    91504,
    90292,
    94025,
    None
  ],
  'delivery_type': [
    'First Class',
    'Standard',
    'Priority',
    'Standard',
    None,
    'Expresss',
    'Standard',
    'Standard',
    None,
    None
  ]
}
addresses=pd.DataFrame(data)
addresses

                      street            city state  zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA   94303.0   First Class
1            1381 9th Avenue   San Francisco    CA   94122.0      Standard
2          1709 Broderick St   San Francisco    CA   94115.0      Priority
3            2640 Steiner St   San Francisco    CA   94123.0      Standard
4               2601 Lyon St   San Francisco    CA   94123.0          None
5  1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA   90292.0      Standard
8    232 Santa Margarita Ave      Menlo Park  None   94025.0          None
9         471 Emerson Street            None  None       NaN          None

# 1.MISSING DATA

.info() tells us which columns are complete and which ones are hiding empty values.

# 2. HANDLE MISSING DATA

###1.  Remove Rows with .dropna()

---> This removes any rows that contain at least one missing value. If only a small number of rows are missing data (and that data isn’t important), we can safely drop those rows with .dropna() which stands for "Drop Not Available.
        cleaned_df = df.dropna()

But what if we only care about missing values in specific columns? We can use subset
        cleaned_df = df.dropna(subset = ['username', 'location'])
    -->This removes rows that have a missing value in the username or location columns.

In [3]:
#Create a DataFrame that removes rows with missing data in any column.
given_data=addresses.dropna()
given_data

                      street            city state  zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA   94303.0   First Class
1            1381 9th Avenue   San Francisco    CA   94122.0      Standard
2          1709 Broderick St   San Francisco    CA   94115.0      Priority
3            2640 Steiner St   San Francisco    CA   94123.0      Standard
5  1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA   90292.0      Standard

In [7]:
# Create a DataFrame that removes rows with missing data in only the class column.
cleaned=addresses.dropna(subset=['zip_code','city'])
cleaned

                      street            city state  zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA   94303.0   First Class
1            1381 9th Avenue   San Francisco    CA   94122.0      Standard
2          1709 Broderick St   San Francisco    CA   94115.0      Priority
3            2640 Steiner St   San Francisco    CA   94123.0      Standard
4               2601 Lyon St   San Francisco    CA   94123.0          None
5  1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA   90292.0      Standard
8    232 Santa Margarita Ave      Menlo Park  None   94025.0          None

###2.Replace Missing Values with .fillna()

-->Imputation means filling in the blanks with a value that makes sense. Your choice on how to do this will depend on the data. Some common choices include:

        1.A default value, like 'Unknown'
            example: df['location'] = df['location'].fillna('Unknown')
            
        
        2.The most common value (the mode)
           example:        # Find the most common value in the column
                             most_common_location = df['location'].mode()[0]
                           # Fill missing values with that value
                             df['location'] = df['location'].fillna(most_common_location)
                             
                             
        3.The average value (if your data is numerical)
            example:        mean_age = df['age'].mean()
                            df['age'] = df['age'].fillna(mean_age)

In [8]:
# Impute the missing zip_code with the average... and hope the mailman delivers it. 
mean_zip=addresses['zip_code'].mean()
addresses['zip_code']=addresses['zip_code'].fillna(mean_zip)

In [9]:
addresses

                      street            city state      zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA  94303.000000   First Class
1            1381 9th Avenue   San Francisco    CA  94122.000000      Standard
2          1709 Broderick St   San Francisco    CA  94115.000000      Priority
3            2640 Steiner St   San Francisco    CA  94123.000000      Standard
4               2601 Lyon St   San Francisco    CA  94123.000000          None
5  1600 Amphitheatre Parkway   Mountain View    CA  94043.000000      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA  91504.000000      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA  90292.000000      Standard
8    232 Santa Margarita Ave      Menlo Park  None  94025.000000          None
9         471 Emerson Street            None  None  93405.555556          None

In [13]:
# Impute the missing state and delivery_type values with the most common values.
most_common=addresses['delivery_type'].mode()[0]
addresses['delivery_type']=addresses['delivery_type'].fillna(most_common)
addresses

                      street            city state      zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA  94303.000000   First Class
1            1381 9th Avenue   San Francisco    CA  94122.000000      Standard
2          1709 Broderick St   San Francisco    CA  94115.000000      Priority
3            2640 Steiner St   San Francisco    CA  94123.000000      Standard
4               2601 Lyon St   San Francisco    CA  94123.000000      Standard
5  1600 Amphitheatre Parkway   Mountain View    CA  94043.000000      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA  91504.000000      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA  90292.000000      Standard
8    232 Santa Margarita Ave      Menlo Park  None  94025.000000      Standard
9         471 Emerson Street            None  None  93405.555556      Standard