# String Manipulation

There are a handful of very helpful .str methods for basic string processing:

.str.lower(): makes everything lowercase

.str.upper(): makes everything uppercase

.str.strip(): removes whitespace from both ends

.str.contains('text'): checks for a substring

.str.replace('old', 'new'): replaces parts of the text

You can even chain these methods together in a single line

In [1]:
import pandas as pd
import random

random.seed(1)

# Different possible RSVP variants
options = ['Yes', 'yes', 'yesss', 'Yep   ', ' yes', 'YES', 'y', 'No  ', 'no', 'N ', 'n', 'no thx']

one_hundred_responses = random.choices(options, k=100)

# Generate fake names for the 100 guests
names = [f'Guest_{i+1}' for i in range(100)]

# Create the DataFrame
responses = pd.DataFrame({
  'name': names,
  'rsvp': one_hundred_responses
})

In [2]:
responses

         name    rsvp
0     Guest_1     yes
1     Guest_2       n
2     Guest_3      N
3     Guest_4  Yep
4     Guest_5     YES
..        ...     ...
95   Guest_96      no
96   Guest_97      N
97   Guest_98       y
98   Guest_99       y
99  Guest_100     YES

[100 rows x 2 columns]

#our job is to process the text of the rsvp column and make each response either 'y' or 'n'
1. Begin by looking at the head or tail of the DataFrame to understand what the data looks like.
2. Then, standardize the capitalization and strip extra spaces of the rsvp column.
3. Finally, use .replace() to turn yes into y and no into n.
4.We can use responses['rsvp'].value_counts() to print out the final number of yes and no responses.

In [4]:
#1
responses.head()

      name    rsvp
0  Guest_1     yes
1  Guest_2       n
2  Guest_3      N
3  Guest_4  Yep
4  Guest_5     YES

In [5]:
responses.tail()

         name rsvp
95   Guest_96   no
96   Guest_97   N
97   Guest_98    y
98   Guest_99    y
99  Guest_100  YES

In [7]:
#2
responses['rsvp']=responses['rsvp'].str.lower().str.strip()

In [8]:
responses.head(10)

       name rsvp
0   Guest_1  yes
1   Guest_2    n
2   Guest_3    n
3   Guest_4  yep
4   Guest_5  yes
5   Guest_6  yes
6   Guest_7   no
7   Guest_8    n
8   Guest_9  yes
9  Guest_10  yes

In [13]:
#3
responses['rsvp']=responses['rsvp'].str.replace('yes','y')
responses['rsvp']=responses['rsvp'].str.replace('yss','y')
responses['rsvp']=responses['rsvp'].str.replace('yep','y')

In [14]:
responses['rsvp']=responses['rsvp'].str.replace('no','n')
responses['rsvp']=responses['rsvp'].str.replace('n thx','n')

In [15]:
responses['rsvp'].value_counts()

rsvp
y    60
n    40
Name: count, dtype: int64