# WRONG DATA TYPES

In [6]:
import pandas as pd
data = {
  'player_name': [
    'Parzival', 'Ar3mis', 'Aech', 'Kirito', 'Azuna',
    'nakedinthewoods', 'Sonny666', 'X.X', 'Fendi_Gucci', 'Professor Chaos'
  ],
  'score': [
    '1500', '2300', '1800', '2,100', '1700',
    '2000', '2200', '1600', '1900', '2k50'
  ],
  'level': [
    12, 15, 13, 14, 12, 
    13, 15, 11, 14, 13
  ],
  'time_solved': [
    '23.5', '35.2', '19.0', '14.8', '3.8',
    '42.5', '5h', '33.2', '4.3', '24.6'
  ]
}
score_Card=pd.DataFrame(data)
score_Card

       player_name  score  level time_solved
0         Parzival   1500     12        23.5
1           Ar3mis   2300     15        35.2
2             Aech   1800     13        19.0
3           Kirito  2,100     14        14.8
4            Azuna   1700     12         3.8
5  nakedinthewoods   2000     13        42.5
6         Sonny666   2200     15          5h
7              X.X   1600     11        33.2
8      Fendi_Gucci   1900     14         4.3
9  Professor Chaos   2k50     13        24.6

# Inspecting Data Types

You can use .dtypes to see the type of each column
SYNTAX:  df.dtypes  -->This will display the column name with in what type of data it has been storing the datas of the column

In [7]:
#Find data type for each and every column
score_Card.dtypes

player_name    object
score          object
level           int64
time_solved    object
dtype: object

# Changing Data Types

After finding the data types for each and every column, now we can change its datatype

#If Pandas is treating a numeric column as a string, we can use pd.to_numeric() to convert the data type.
    
    ------>  example: df['age'] = pd.to_numeric(df['age'])

--> This will change the age column to be numeric. But this only works if every value in the age column can be interpreted as a number.
If one of the values is something like 'twenty years old', Pandas won't know how to turn that into 20. In this case, pd.to_numeric will throw an error!

To solve this, we can use the parameter errors = 'coerce'

example: df['age'] = pd.to_numeric(df['age'], errors = 'coerce')

-->When using this parameter, rather than throwing an error for values that it can not convert, Pandas will convert them to NaN (not a number).

In [13]:
# convert the appropriate columns to numeric types, and then find the average (.mean()) high score and time played.
score_Card['score']=pd.to_numeric(score_Card['score'],errors='coerce')
score_Card['level']=pd.to_numeric(score_Card['level'],errors='coerce')
score_Card['time_solved']=pd.to_numeric(score_Card['time_solved'],errors='coerce')
score_Card.dtypes

player_name     object
score          float64
level            int64
time_solved    float64
dtype: object

In [16]:
#finding the mean of numeric column
score_Card['score'].mean()

np.float64(13.2)

In [17]:
score_Card['level'].mean()

np.float64(13.2)

In [18]:
score_Card['time_solved'].mean()

np.float64(22.322222222222223)

In [19]:
score_Card

       player_name   score  level  time_solved
0         Parzival  1500.0     12         23.5
1           Ar3mis  2300.0     15         35.2
2             Aech  1800.0     13         19.0
3           Kirito     NaN     14         14.8
4            Azuna  1700.0     12          3.8
5  nakedinthewoods  2000.0     13         42.5
6         Sonny666  2200.0     15          NaN
7              X.X  1600.0     11         33.2
8      Fendi_Gucci  1900.0     14          4.3
9  Professor Chaos     NaN     13         24.6