# 1.Importing Pandas

In [1]:
import pandas as pd

# 2. Opening a Local CSV file

In [2]:
pd.read_csv("insurance.csv")

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

# 3. Opening a csv file from an URL

In [4]:
import requests
from io import StringIO
url=""
headers={"give the link of the dataset"}
req=requests.get(url,headers=headers)
data=StringIO(req.test)

pd.read_csv(data)

MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?

# 4. Sep  Parameter

In [4]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=['sno','name','release_year','rating','votes','genres'])

,sno,name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

# 5. Index_col parameter

In [9]:
pd.read_csv('insurance.csv')

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

# 6. Header parameter

In [14]:
pd.read_csv('insurance.csv',header=1) #header=1, helps to start the row from 1

      19  female    27.9  0  yes  southwest    16884.924
0     18    male  33.770  1   no  southeast   1725.55230
1     28    male  33.000  3   no  southeast   4449.46200
2     33    male  22.705  0   no  northwest  21984.47061
3     32    male  28.880  0   no  northwest   3866.85520
4     31  female  25.740  0   no  southeast   3756.62160
...   ..     ...     ... ..  ...        ...          ...
1332  50    male  30.970  3   no  northwest  10600.54830
1333  18  female  31.920  0   no  northeast   2205.98080
1334  18  female  36.850  0   no  southeast   1629.83350
1335  21  female  25.800  0   no  southwest   2007.94500
1336  61  female  29.070  0  yes  northwest  29141.36030

[1337 rows x 7 columns]

# 7.use_cols parame

In [15]:
pd.read_csv('insurance.csv',usecols=['age','children','bmi','smoker','charges'])

      age     bmi  children smoker      charges
0      19  27.900         0    yes  16884.92400
1      18  33.770         1     no   1725.55230
2      28  33.000         3     no   4449.46200
3      33  22.705         0     no  21984.47061
4      32  28.880         0     no   3866.85520
...   ...     ...       ...    ...          ...
1333   50  30.970         3     no  10600.54830
1334   18  31.920         0     no   2205.98080
1335   18  36.850         0     no   1629.83350
1336   21  25.800         0     no   2007.94500
1337   61  29.070         0    yes  29141.36030

[1338 rows x 5 columns]

# 8. Squeeze parameters

In [17]:
pd.read_csv('insurance.csv', usecols=['charges']).squeeze('columns')

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

# 9. dtypes parameter

In [18]:
pd.read_csv('insurance.csv',dtype={'bmi':int}).info()

ValueError: cannot safely convert passed user dtype of int64 for float64 dtyped data in column 2